services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    image: bgbluster-backend:latest
    container_name: bgbluster-backend
    ports:
      - "8000:8000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - ./Backend:/app
    networks:
      - bgbluster-network
    restart: unless-stopped
    depends_on:
      - frontend

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    image: bgbluster-frontend:latest
    container_name: bgbluster-frontend
    ports:
      - "3000:80"
    volumes:
      - ./Frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - bgbluster-network
    restart: unless-stopped

networks:
  bgbluster-network:
    driver: bridge